name: Densuke Watcher

on:
  push:
    branches: [ main ]   # 必要ならブランチ名を変更
  workflow_dispatch:      # 手動実行も可能

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 何が未追跡なのか見たい場合は有効化
      # - name: Show git status (debug)
      #   run: |
      #     git status
      #     git diff --name-only || true
      #     git ls-files --others --exclude-standard || true

      - name: Run watcher
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          # prev.html はリポジトリ外に保存（作業ツリーを汚さない）
          SNAPSHOT_HTML: ${{ runner.temp }}/prev.html
        run: |
          python Seminer.py
