name: Densuke Notifier

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'prev.html'          # スナップショット更新だけでは起動しない
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write            # ← これがないと push できない

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notifier
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: python Seminer.py

      - name: Commit snapshot (prev.html)
        if: always()
        run: |
          git pull --rebase
          git add prev.html
          if git diff --cached --quiet; then
            echo "no changes"
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Update snapshot [skip ci]"
            git push
          fi
