name: Densuke Watcher

on:
  push:             # どのブランチのpushでも起動
    branches:
      - '**'
  workflow_dispatch: {}
  schedule:
    - cron: '*/15 * * * *'  # 15分毎（UTC基準）

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Debug triggers (optional)
        if: ${{ github.event_name != 'schedule' }}   # 任意
        run: |
          echo "event: ${{ github.event_name }}"
          echo "ref:   ${{ github.ref }}"
          echo "sha:   ${{ github.sha }}"

      - name: Run watcher
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          # リポ外に保存（作業ツリーを汚さない）
          SNAPSHOT_HTML: ${{ runner.temp }}/prev.html
        run: |
          python Seminer.py
