# .github/workflows/densuke-watcher.yml
name: Densuke Watcher (scheduled)

on:
  schedule:
    - cron: '*/15 * * * *'   # 15分ごと（UTC）
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # prev.html をコミットするために必要

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Clean working tree (reset to origin/main)
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Run watcher
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          SNAPSHOT_HTML: prev.html
        run: |
          python Seminer.py

      - name: Commit & push snapshot if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "Update snapshot [skip ci]"
            git push origin HEAD:main
          fi
